rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server
ui:
  ssl: false
  host: 0.0.0.0
  port: 4000
browseBy:
  showThumbnails: false
  # When set to active, users will be able to switch to the use of this language in the user interface.
languages:
  - code: en
    label: English
    active: true
  - code: tr
    label: Türkçe
    active: true